language: python
python:
  - "2.7"

install:
  - "pip install twisted"
  - "pip install requests"
  - "pip install python-dateutil"
  - "pip install feedparser"

script: trial plugins

notifications:
  irc: "irc.chalmers.it#platinumshrimp"
